name: Linux Build Check

on:
  push:
    branches: [ ym ]
  pull_request:
    branches: [ ym ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -S example/sndh2wav -B example/sndh2wav/build -DCMAKE_BUILD_TYPE=Release

      - name: Compile project
        run: cmake --build example/sndh2wav/build --config Release
